# Generated by Django 3.1.4 on 2021-01-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post'),
            preserve_default=False,
        ),
    ]
